# Generated by Django 3.1.3 on 2021-06-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reportId', models.AutoField(primary_key=True, serialize=False)),
                ('userId1', models.IntegerField(verbose_name='发起订单用户id')),
                ('userName1', models.CharField(default='default-username', max_length=100)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('userId2', models.IntegerField(blank=True, null=True, verbose_name='接单用户id')),
                ('userName2', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
