# Generated by Django 3.1.3 on 2021-06-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0002_report_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='userName1',
            new_name='userName',
        ),
        migrations.RemoveField(
            model_name='report',
            name='userId1',
        ),
        migrations.RemoveField(
            model_name='report',
            name='userId2',
        ),
        migrations.RemoveField(
            model_name='report',
            name='userName2',
        ),
        migrations.AddField(
            model_name='report',
            name='userId',
            field=models.IntegerField(default=1, verbose_name='报告撰写用户id'),
            preserve_default=False,
        ),
    ]
