# Generated by Django 3.1.3 on 2021-06-04 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FormTemplate', '0003_formtemplate_subtype'),
        ('Report', '0003_auto_20210604_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='formId',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='FormTemplate.formtemplate'),
            preserve_default=False,
        ),
    ]
