# Generated by Django 3.1.3 on 2021-06-02 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FormTemplate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('formtemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FormTemplate.formtemplate')),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('ddl', models.DateField()),
                ('negotiateTime', models.DateField()),
            ],
            bases=('FormTemplate.formtemplate',),
        ),
    ]
