# Generated by Django 3.1.3 on 2021-06-02 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormTemplate', '0001_initial'),
        ('Form1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormTemplate',
            new_name='Form1',
        ),
    ]
