# Generated by Django 3.1.3 on 2021-06-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form1', '0002_auto_20210603_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='form1',
            name='percentage',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
