# Generated by Django 3.1.3 on 2021-06-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('formId', models.AutoField(primary_key=True, serialize=False)),
                ('userId1', models.IntegerField(verbose_name='发起订单用户id')),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('significanceBit', models.BooleanField(default=True)),
                ('taken', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
                ('userId2', models.IntegerField(blank=True, null=True, verbose_name='接单用户id')),
            ],
        ),
    ]
