# Generated by Django 3.1.3 on 2021-06-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormTemplate', '0002_auto_20210603_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='subtype',
            field=models.IntegerField(default=1),
        ),
    ]
