# Generated by Django 3.1.3 on 2021-06-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form2',
            name='form1Id',
            field=models.IntegerField(default=-1),
        ),
    ]
